/// SQL keywords recognized by the parser.
///
/// The lexer emits all identifiers as `TokenKind::BareWord`. The parser uses
/// `Parser::at_keyword()` with case-insensitive comparison to distinguish
/// keywords from regular identifiers. This enum lists every keyword the
/// parser currently needs to recognize.
#[derive(Debug, Copy, Clone)]
#[allow(dead_code)]
pub enum Keyword {
    // Clauses
    Select,
    From,
    Where,
    Order,
    By,
    Group,
    Having,
    Limit,
    Offset,
    With,
    As,
    On,
    Using,
    Between,
    In,
    Like,
    Is,
    Not,
    Case,
    When,
    Then,
    Else,
    End,
    Cast,
    Distinct,
    All,
    Exists,

    // Logical operators
    And,
    Or,

    // Joins
    Join,
    Inner,
    Left,
    Right,
    Full,
    Outer,
    Cross,
    Global,
    Any,
    Semi,
    Anti,
    Asof,
    Natural,
    Array,
    Final,

    // ORDER BY modifiers
    Asc,
    Desc,
    Nulls,
    First,
    Last,

    // GROUP BY modifiers
    Totals,
    Rollup,
    Cube,

    // Set operations
    Union,
    Except,
    Intersect,

    // DML
    Insert,
    Into,
    Values,
    Delete,
    Update,
    Set,

    // DDL
    Create,
    Alter,
    Drop,
    Detach,
    Attach,
    Rename,
    Truncate,
    Show,
    Use,
    Optimize,
    System,

    // Table keywords
    Table,
    View,
    Database,
    Dictionary,
    Function,
    Materialized,
    Temporary,
    If,

    // Column keywords
    Default,
    Codec,
    Ttl,
    Comment,
    Primary,
    Key,

    // ClickHouse-specific clauses
    Prewhere,
    Settings,
    Format,
    Sample,

    // Literals
    Null,
    True,
    False,

    // Types / INTERVAL
    Interval,
}

impl Keyword {
    pub fn as_str(&self) -> &'static str {
        match self {
            Keyword::Select => "SELECT",
            Keyword::From => "FROM",
            Keyword::Where => "WHERE",
            Keyword::Order => "ORDER",
            Keyword::By => "BY",
            Keyword::Group => "GROUP",
            Keyword::Having => "HAVING",
            Keyword::Limit => "LIMIT",
            Keyword::Offset => "OFFSET",
            Keyword::With => "WITH",
            Keyword::As => "AS",
            Keyword::On => "ON",
            Keyword::Using => "USING",
            Keyword::Between => "BETWEEN",
            Keyword::In => "IN",
            Keyword::Like => "LIKE",
            Keyword::Is => "IS",
            Keyword::Not => "NOT",
            Keyword::Case => "CASE",
            Keyword::When => "WHEN",
            Keyword::Then => "THEN",
            Keyword::Else => "ELSE",
            Keyword::End => "END",
            Keyword::Cast => "CAST",
            Keyword::Distinct => "DISTINCT",
            Keyword::All => "ALL",
            Keyword::Exists => "EXISTS",
            Keyword::And => "AND",
            Keyword::Or => "OR",
            Keyword::Join => "JOIN",
            Keyword::Inner => "INNER",
            Keyword::Left => "LEFT",
            Keyword::Right => "RIGHT",
            Keyword::Full => "FULL",
            Keyword::Outer => "OUTER",
            Keyword::Cross => "CROSS",
            Keyword::Global => "GLOBAL",
            Keyword::Any => "ANY",
            Keyword::Semi => "SEMI",
            Keyword::Anti => "ANTI",
            Keyword::Asof => "ASOF",
            Keyword::Natural => "NATURAL",
            Keyword::Array => "ARRAY",
            Keyword::Final => "FINAL",
            Keyword::Asc => "ASC",
            Keyword::Desc => "DESC",
            Keyword::Nulls => "NULLS",
            Keyword::First => "FIRST",
            Keyword::Last => "LAST",
            Keyword::Totals => "TOTALS",
            Keyword::Rollup => "ROLLUP",
            Keyword::Cube => "CUBE",
            Keyword::Union => "UNION",
            Keyword::Except => "EXCEPT",
            Keyword::Intersect => "INTERSECT",
            Keyword::Insert => "INSERT",
            Keyword::Into => "INTO",
            Keyword::Values => "VALUES",
            Keyword::Delete => "DELETE",
            Keyword::Update => "UPDATE",
            Keyword::Set => "SET",
            Keyword::Create => "CREATE",
            Keyword::Alter => "ALTER",
            Keyword::Drop => "DROP",
            Keyword::Detach => "DETACH",
            Keyword::Attach => "ATTACH",
            Keyword::Rename => "RENAME",
            Keyword::Truncate => "TRUNCATE",
            Keyword::Show => "SHOW",
            Keyword::Use => "USE",
            Keyword::Optimize => "OPTIMIZE",
            Keyword::System => "SYSTEM",
            Keyword::Table => "TABLE",
            Keyword::View => "VIEW",
            Keyword::Database => "DATABASE",
            Keyword::Dictionary => "DICTIONARY",
            Keyword::Function => "FUNCTION",
            Keyword::Materialized => "MATERIALIZED",
            Keyword::Temporary => "TEMPORARY",
            Keyword::If => "IF",
            Keyword::Default => "DEFAULT",
            Keyword::Codec => "CODEC",
            Keyword::Ttl => "TTL",
            Keyword::Comment => "COMMENT",
            Keyword::Primary => "PRIMARY",
            Keyword::Key => "KEY",
            Keyword::Prewhere => "PREWHERE",
            Keyword::Settings => "SETTINGS",
            Keyword::Format => "FORMAT",
            Keyword::Sample => "SAMPLE",
            Keyword::Null => "NULL",
            Keyword::True => "TRUE",
            Keyword::False => "FALSE",
            Keyword::Interval => "INTERVAL",
        }
    }
}
